query Stream($id: String!) {
  stream(id: $id) {
    id
    name
    description
    isPublic
    createdAt
    updatedAt
    collaborators {
      id
      name
      role
      company
      avatar
    }
    branches {
      totalCount
      cursor
      items {
        id
        name
        description
        commits {
          totalCount
        }
      }
    }
    commits {
      totalCount
    }
  }
}
