query Stream($id: String!) {
  stream(id: $id) {
    id
    commits {
      totalCount
      items{
        id
        authorId
        authorName
        authorAvatar
        createdAt
        message
      }
    }
  }
}
