query {
  user {
    id
    email
    name
    bio
    company
    avatar
    verified
    profiles
    role
    streams(limit: 25) {
      totalCount
      cursor
      items {
        id
        name
        description
        isPublic
        createdAt
        updatedAt
        collaborators {
          id
          name
          company
          avatar
          role
        }
        commits {
          totalCount
        }
        branches {
          totalCount
        }
      }
    }
    commits(limit: 25) {
      totalCount
      cursor
      items {
        id
        message
        streamId
        streamName
        createdAt
      }
    }
  }
}
