{{- if .Values.preview_service.enabled }}
{{- if .Values.preview_service.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: speckle-preview-service
  namespace: {{ .Values.namespace }}
  labels:
{{ include "preview_service.labels" . | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: speckle-preview-service
  minReplicas: {{ .Values.preview_service.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.preview_service.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.preview_service.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.preview_service.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.preview_service.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.preview_service.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
