{{- if .Values.preview_service.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "preview_service.name" $ }}
  namespace: {{ .Values.namespace | quote }}
  labels:
{{ include "preview_service.labels" $ | indent 4 }}
  annotations:
    "kubernetes.io/enforce-mountable-secrets": "true"
automountServiceAccountToken: false
secrets:
  - name: {{ default .Values.secretName .Values.db.connectionString.secretName }}
{{- if .Values.featureFlags.workspacesMultiRegionEnabled }}
  - name: {{ default .Values.secretName .Values.multiRegion.config.secretName }}
{{- end }}
{{- end -}}
