'use strict'

module.exports = [
  'Amenhotep, son of Hapu',
  'Imhotep',
  'Yu Hao',
  'Villard de Honnecourt',
  'Peter Parler',
  'Leon Battista Alberti',
  'Donato Bramante',
  'Filippo Brunelleschi',
  'Michelozzo Michelozzi',
  'Bernardo Rossellino',
  'Leonardo da Vinci',
  'Vincenzo Scamozzi',
  'Sebastiano Serlio',
  'Lambert Sustris',
  'Pellegrino Tibaldi',
  'Giorgio Vasari',
  'Gian Lorenzo Bernini',
  'Francesco Borromini',
  'Ustad Ahmad Lahauri',
  'Jacob van Campen',
  'Johann Dientzenhofer',
  'Tumas Dingli',
  'Léopold Durand',
  'Pietro Paolo Floriani',
  'François Mansart',
  'Andreas Schlüter',
  'Robert Adam',
  'John Carr of York',
  'William Kent',
  'Jacques-Germain Soufflot',
  'Manuel Caetano de Sousa',
  'William Thornton',
  'James Fowler (architect)|James Fowler',
  'Thomas Fuller (architect)|Thomas Fuller',
  'Friedrich von Gärtner',
  'Edward William Godwin',
  'Philip Charles Hardwick',
  'Victor Horta',
  'William LeBaron Jenney',
  'Leo von Klenze',
  'Henri Labrouste',
  'Alexander Wadsworth Longfellow, Jr.',
  'Auguste de Montferrand',
  'John Nash (architect)|John Nash',
  'Joseph Maria Olbrich',
  'Joseph Paxton',
  'Francis Penrose',
  'Francis Petre',
  'Augustus Pugin',
  'Karl Friedrich Schinkel',
  'Gottfried Semper',
  'J. J. Stevenson',
  'Louis Sullivan',
  'Thomas Telford',
  'Eugène Viollet-le-Duc',
  'Otto Wagner',
  'John Dodsley Webster',

  'Alvar Aalto',
  'Max Abramovitz',
  'Gunnar Asplund',
  'Luis Barragán',
  'Peter Behrens',
  'Pietro Belluschi',
  'Antonio Bilbao La Vieja',
  'Marcel Breuer',
  'Le Corbusier',
  'Charles Eames',
  'Buckminster Fuller',
  'Antoni Gaudí',
  'Walter Gropius',
  'Hector Guimard',
  'Victor Horta',
  'Friedensreich Hundertwasser',
  'Arne Jacobsen',
  'Philip Johnson',
  'Josep Maria Jujol',
  'Louis Kahn',
  'Károly Kós',
  'Kisho Kurokawa',
  'Edgar-Johan Kuusik',
  'Ricardo Legorreta',
  'Jan Letzel',
  'Liang Sicheng',
  'Adolf Loos',
  'Charles Rennie Mackintosh',
  'Wayne McAllister',
  'Konstantin Melnikov',
  'Erich Mendelsohn',
  'Paulo Mendes da Rocha',
  'Henry Mercer',
  'Giovanni Michelucci',
  'Ludwig Mies van der Rohe',
  'Riccardo Morandi',
  'Luigi Moretti',
  'Pier Luigi Nervi',
  'Ngo Viet Thu',
  'Oscar Niemeyer',
  'Oscar Nitzchke',
  'Frei Otto',
  'Mihály Párkányi',
  'Arthur Peabody',
  'I. M. Pei',
  'Stjepan Planić',
  'Hans Poelzig',
  'William Gray Purcell',
  'Steen Eiler Rasmussen',
  'Aldo Rossi',
  'Eero Saarinen',
  'Rogelio Salmona',
  'Guðjón Samúelsson',
  'Carlo Scarpa',
  'Elisabeth Scott',
  'Albert Speer',
  'Kenzo Tange',
  'Jørn Utzon',
  'Geoffrey Wooding',
  'Frank Lloyd Wright',
]