'use strict'

module.exports = [
  'Amenhotep, son of Hapu',
  'Imhotep',
  'Yu Hao',
  'Villard de Honnecourt',
  'Peter Parler',
  'Leon Battista Alberti',
  'Donato Bramante',
  'Filippo Brunelleschi',
  'Michelozzo Michelozzi',
  'Bernardo Rossellino',
  'Leonardo da Vinci',
  'Vincenzo Scamozzi',
  'Sebastiano Serlio',
  'Lambert Sustris',
  'Pellegrino Tibaldi',
  'Giorgio Vasari',
  'Gian Lorenzo Bernini',
  'Francesco Borromini',
  'Ustad Ahmad Lahauri',
  'Jacob van Campen',
  'Johann Dientzenhofer',
  'Tumas Dingli',
  'Léopold Durand',
  'Pietro Paolo Floriani',
  'François Mansart',
  'Andreas Schlüter',
  'Robert Adam',
  'John Carr of York',
  'William Kent',
  'Jacques-Germain Soufflot',
  'Manuel Caetano de Sousa',
  'William Thornton',
  'James Fowler (architect)|James Fowler',
  'Thomas Fuller (architect)|Thomas Fuller',
  'Friedrich von Gärtner',
  'Edward William Godwin',
  'Philip Charles Hardwick',
  'Victor Horta',
  'William LeBaron Jenney',
  'Leo von Klenze',
  'Henri Labrouste',
  'Alexander Wadsworth Longfellow, Jr.',
  'Auguste de Montferrand',
  'John Nash (architect)|John Nash',
  'Joseph Maria Olbrich',
  'Joseph Paxton',
  'Francis Penrose',
  'Francis Petre',
  'Augustus Pugin',
  'Karl Friedrich Schinkel',
  'Gottfried Semper',
  'J. J. Stevenson',
  'Louis Sullivan',
  'Thomas Telford',
  'Eugène Viollet-le-Duc',
  'Otto Wagner',
  'John Dodsley Webster',
  'Alvar Aalto',
  'Max Abramovitz',
  'Tadao Ando',
  'Gunnar Asplund',
  'Luis Barragán',
  'Peter Behrens',
  'Pietro Belluschi',
  'Antonio Bilbao La Vieja',
  'Mario Botta',
  'Marcel Breuer',
  'Santiago Calatrava',
  'David Chipperfield',
  'Le Corbusier',
  'Charles Eames',
  'Peter Eisenman',
  'Aldo van Eyck',
  'Norman Foster',
  'Buckminster Fuller',
  'Antoni Gaudí',
  'Frank Gehry',
  'Noemí Goytia',
  'Nicholas Grimshaw',
  'Walter Gropius',
  'Hector Guimard',
  'Michael Hopkins',
  'Victor Horta',
  'Friedensreich Hundertwasser',
  'Arata Isozaki',
  'Arne Jacobsen',
  'Peter Janesch',
  'Philip Johnson',
  'Josep Maria Jujol',
  'Louis Kahn',
  'Kendrick Bangs Kellogg',
  'Hans Kollhoff',
  'Rem Koolhaas',
  'Károly Kós',
  'Kisho Kurokawa',
  'Edgar-Johan Kuusik',
  'Ricardo Legorreta',
  'Jan Letzel',
  'Liang Sicheng',
  'Daniel Libeskind',
  'Adolf Loos',
  'Charles Rennie Mackintosh',
  'Wayne McAllister',
  'Konstantin Melnikov',
  'Erich Mendelsohn',
  'Paulo Mendes da Rocha',
  'Henry Mercer',
  'Giovanni Michelucci',
  'Ludwig Mies van der Rohe',
  'Rafael Moneo',
  'Riccardo Morandi',
  'Luigi Moretti',
  'Charles Willard Moore',
  'Michel Mossessian',
  'Glenn Murcutt',
  'Pier Luigi Nervi',
  'Ngo Viet Thu',
  'Oscar Niemeyer',
  'Oscar Nitzchke',
  'Frei Otto',
  'Mihály Párkányi',
  'John Pawson',
  'Arthur Peabody',
  'I. M. Pei',
  'Stjepan Planić',
  'Hans Poelzig',
  'William Gray Purcell',
  'Steen Eiler Rasmussen',
  'Richard Rogers',
  'Aldo Rossi',
  'Eero Saarinen',
  'Moshe Safdie',
  'Rogelio Salmona',
  'Guðjón Samúelsson',
  'Carlo Scarpa',
  'Elisabeth Scott',
  'Alvaro Siza',
  'Eduardo Souto de Moura',
  'Albert Speer',
  'Kenzo Tange',
  'Jørn Utzon',
  'Geoffrey Wooding',
  'Frank Lloyd Wright',
  'Peter Zumthor',
  'Arif Hasan',
  'Atsushi Kitagawara',
  'Bjarke Ingels',
  'Christina Cho',
  'Daniel Libeskind',
  'David Adjaye',
  'David Randall Hertz',
  'Dominique Gauzin-Müller',
  'Dy Proeung',
  'Erick van Egeraat',
  'Eugene Pandala',
  'Jimenez Lai',
  'Kazuyo Sejima',
  'Kengo Kuma',
  'Marco Casagrande',
  'Mariam Kamara',
  'Massimiliano Fuksas',
  'Michel Abboud',
  'Norman Foster',
  'Odile Decq',
  'Olajumoke Adenowo',
  'Peter Eisenman',
  'Rem Koolhaas',
  'Shigeru Ban',
  'Sou Fujimoto',
  'Steven Holl',
  'Sunay Erdem',
  'Thomas Doerr',
  'Thomas Herzog',
  'Tony Fretton',
  'Toyo Ito',
  'Zaha Hadid',
  'Enamul Karim Nirjhar',
  'Neri Oxman',
  'Renzo Piano',
  'Dimitris Potiropoulos',
  'Philippe Rahm',
  'Richard Rogers',
  'Fernando Romero',
  'Sheila Sri Prakash',
  'Sergei Tchoban',
  'Jack Travis',
  'Victor Vechersky',
  'Wang Shu',
  'Gert Wingårdh',
  'Jun Xia'
]