apiVersion: v1
kind: Service
metadata:
  name: speckle-server
  namespace: {{ .Values.namespace }}
  labels:
    app: speckle-server
    project: speckle-server
spec:
  selector:
    app: speckle-server
    project: speckle-server
  ports:
    - protocol: TCP
      name: web
      port: 3000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: speckle-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: speckle-frontend
    project: speckle-server
spec:
  selector:
    app: speckle-frontend
    project: speckle-server
  ports:
    - protocol: TCP
      name: www
      port: 80
      targetPort: www
---
apiVersion: v1
kind: Service
metadata:
  name: speckle-preview-service-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app: speckle-preview-service-metrics
    project: speckle-server
spec:
  selector:
    app: speckle-preview-service
    project: speckle-server
  ports:
    - protocol: TCP
      name: web
      port: 9094
      targetPort: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: speckle-fileimport-service-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app: speckle-fileimport-service-metrics
    project: speckle-server
spec:
  selector:
    app: speckle-fileimport-service
    project: speckle-server
  ports:
    - protocol: TCP
      name: web
      port: 9093
      targetPort: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: speckle-webhook-service-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app: speckle-webhook-service
    project: speckle-server
spec:
  selector:
    app: speckle-webhook-service
    project: speckle-server
  ports:
    - protocol: TCP
      name: web
      port: 9095
      targetPort: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: speckle-monitoring-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app: speckle-monitoring
    project: speckle-server
spec:
  selector:
    app: speckle-monitoring
    project: speckle-server
  ports:
    - protocol: TCP
      name: web
      port: 9092
      targetPort: metrics
