compressionLevel: mixed

enableGlobalCache: false

enableMirror: false

nodeLinker: node-modules

yarnPath: ./.yarn/releases/yarn-4.5.0.cjs

# Some items do not respect the enableGlobalCache: false setting
# and still use the global cache. This is a workaround to ensure they
# use the local directory instead.
globalFolder: ./.yarn/global

cacheFolder: ./.yarn/cache
