codecov:
  notify:
    notify_error: true
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        target: 90% #overall project/ repo coverage
      server:
        target: 70%
        flags:
          - server
      shared:
        target: 70%
        flags:
          - shared
    patch:
      default:
        target: 90% #overall project/ repo coverage
      server:
        target: 90%
        flags:
          - server
      shared:
        target: 100%
        flags:
          - shared

flags:
  server:
    paths:
      - packages/server/coverage/lcov.info
    carryforward: false
  shared:
    paths:
      - packages/shared/coverage/coverage-final.json
    carryforward: false
