print('🚀 Deploying Speckle Server via Tilt...')

# we limit tilt to run only on the kind cluster
allow_k8s_contexts(['kind-speckle-server'])
if k8s_context() != 'kind-speckle-server':
  fail('Failing early as tilt should only ever connect to kind-speckle-server.')

# Install extensions
load('ext://helm_remote', 'helm_remote')
load('ext://k8s_yaml_glob', 'k8s_yaml_glob')

# Create namespaces
k8s_yaml_glob('./manifests/*.namespace.yaml')

# Install volumes
k8s_yaml('./manifests/postgres.pv.yaml')
k8s_yaml('./manifests/postgres.pvc.yaml')
k8s_yaml('./manifests/minio.pv.yaml')
k8s_yaml('./manifests/minio.pvc.yaml')

# Update CoreDNS to allow for local resolution of services internally (i.e. speckle.internal will be routed to nginx)
local(command='./coredns-up.sh')

# Install speckle pod-priority and secrets
k8s_yaml('./manifests/priorityclass.yaml')
k8s_yaml('./manifests/speckle-server.secret.yaml')

# Install charts
helm_remote('postgresql',
            namespace='postgres',
            repo_name='oci://registry-1.docker.io/bitnamicharts',
            values=['./values/postgres.values.yaml'],
            version='^12.0.0')

helm_remote('minio',
            namespace='minio',
            repo_name='oci://registry-1.docker.io/bitnamicharts',
            values=['./values/minio.values.yaml'],
            version='^12.0.0')

helm_remote('redis',
            namespace='redis',
            repo_name='oci://registry-1.docker.io/bitnamicharts',
            values=['./values/redis.values.yaml'],
            version='^18.0.0')

# errors with `no matches for kind "DaemonSet" in version "extensions/v1beta1"`
# but `kubectl get --raw /apis ` and v1.
# The Helm Chart should identify and template correctly: https://github.com/search?q=repo%3Aprometheus-community%2Fhelm-charts+rbac.authorization.k8s.io%2Fv1beta1+path%3Acharts%2F&type=code
# It seems that the chart is not generated correctly.
# helm_remote('prometheus',
#             repo_name='prometheus-operator-crds',
#             namespace='prometheus',
#             repo_url='https://prometheus-community.github.io/helm-charts',
#             values=['./values/prometheus-operator-crds.values.yaml'],
#             version='^7.0.0')

#nginx should be deployed as the last dependency as it opens ports to services
#it expects these services to exist, which are created by the helm charts above
helm_remote('ingress-nginx',
            repo_name='ingress-nginx',
            namespace='ingress-nginx',
            repo_url='https://kubernetes.github.io/ingress-nginx',
            values=['./values/nginx.values.yaml'],
            version='^4.8.0')

# helm_remote('speckle-server',
#             repo_name='speckle-server',
#             namespace='speckle-server',
#             repo_url='https://specklesystems.github.io/helm',
#             values=['./values/speckle-server.values.yaml'])

k8s_yaml(helm('./../../utils/helm/speckle-server',
              values=['./values/speckle-server.values.yaml'],
              namespace='speckle-server',
              name='speckle-server'
              ))