apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "frontend.name" $ }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "frontend.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
{{ include "frontend.selectorLabels" . | indent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # only allow ingress from our within our cluster, i.e. the ingress (loadbalancer)
    - from:
        - namespaceSelector: {}
      ports:
        - port: www
  egress: [] # block all egress
