{{- if .Values.frontend.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "frontend.name" $ }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "frontend.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
{{ include "frontend.selectorLabels" . | indent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # allow ingress from the loadbalancer
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.ingress.namespace }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Values.ingress.controllerName }}
      ports:
        - port: www
  egress: [] # block all egress
{{- end -}}
