{{- if not .Values.frontend_2.enabled -}}
{{- if (and (.Values.frontend.networkPolicy.enabled) (eq .Values.networkPlugin.type "cilium")) -}}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "frontend.name" $ }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "frontend.labels" . | indent 4 }}
spec:
  endpointSelector:
    matchLabels:
{{ include "frontend.selectorLabels" . | indent 6 }}
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: {{ .Values.ingress.namespace }}
{{ include "speckle.ingress.selector.pod" $ | indent 12 }}
      toPorts:
        - ports:
            - port: "www"
              protocol: TCP
  egressDeny:
    - toEntities:
        - "all"
{{- end }}
{{- end -}}
