{{- if not .Values.frontend_2.enabled -}}
{{- if .Values.frontend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontend.name" $ }}
  namespace: {{ .Values.namespace | quote }}
  labels:
{{ include "frontend.labels" $ | indent 4 }}
  annotations:
    "kubernetes.io/enforce-mountable-secrets": "true"
automountServiceAccountToken: false
secrets: [] # no access to any secret
{{- end -}}
{{- end -}}
