{{- if .Values.frontend_2.enabled -}}
{{- if (and (.Values.frontend_2.networkPolicy.enabled) (eq .Values.networkPlugin.type "kubernetes")) -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "frontend_2.name" $ }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "frontend_2.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
{{ include "frontend_2.selectorLabels" . | indent 6 }}
  policyTypes:
    - Ingress
  ingress:
    # allow ingress from the loadbalancer
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.ingress.namespace }}
          podSelector:
            matchLabels:
{{ include  "speckle.ingress.selector.pod" $ | indent 14 }}
      ports:
        - port: www
  egress:
    # allow access to DNS
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
    # allow egress to speckle-server
    - to:
        - podSelector:
            matchLabels:
{{ include "server.selectorLabels" $ | indent 16 }}
      ports:
        - port: 3000
    # redis
{{ include "speckle.networkpolicy.egress.redis" $ | indent 4 }}
{{- end -}}
{{- end -}}
