controller:
  # We must set the kind cluster listen address for every port to '127.0.0.1' when hostNetwork is true, see ./deploy/local/cluster-config.yaml
  hostNetwork: true
  admissionWebhooks:
    enabled: false
  # progressDeadlineSeconds: 600 #HACK helm chart was complaining that this was less than minReadySeconds https://github.com/kubernetes/ingress-nginx/blob/c72441585e1ab1a32df86e760613d36fa804315d/charts/ingress-nginx/templates/controller-deployment.yaml#L26
tcp:
  5433: 'postgres/postgresql:5432'
  6380: 'valkey/valkey-primary:6379'
  9002: 'minio/minio:9000'
