#!/bin/bash
set -e

echo Running Speckle Server initial database setup 

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $SPECKLE_DB_USER WITH PASSWORD '$SPECKLE_DB_PASSWORD';
    CREATE DATABASE $SPECKLE_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $SPECKLE_DB_NAME TO $SPECKLE_DB_USER;
EOSQL