{{- if (and ( or .Values.s3.endpoint .Values.s3.configMap.enabled ) .Values.fileimport_service.serviceAccount.create) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fileimport_service.name" $ }}
  namespace: {{ .Values.namespace | quote }}
  labels:
{{ include "fileimport_service.labels" $ | indent 4 }}
  annotations:
    "kubernetes.io/enforce-mountable-secrets": "true"
automountServiceAccountToken: false
secrets:
  - name: {{ default .Values.secretName .Values.db.connectionString.secretName }}
{{- end -}}
