{{- if .Values.fileimport_service.enabled }}
{{- if (and ( or .Values.s3.endpoint .Values.s3.configMap.enabled ) .Values.fileimport_service.serviceAccount.create) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fileimport_service.name" $ }}
  namespace: {{ .Values.namespace | quote }}
  labels:
{{ include "fileimport_service.labels" $ | indent 4 }}
  annotations:
    "kubernetes.io/enforce-mountable-secrets": "true"
automountServiceAccountToken: false
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
secrets:
  - name: {{ default .Values.secretName .Values.db.connectionString.secretName }}
  - name: {{ default .Values.secretName .Values.redis.connectionString.secretName }}
{{- if .Values.featureFlags.workspacesMultiRegionEnabled }}
  - name: {{ default .Values.secretName .Values.multiRegion.config.secretName }}
{{- end }}
{{- end -}}
{{- end }}
