apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-region1-pv
  namespace: minio-region1
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /minio-region1-volume
