apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-region1-pvc
  namespace: minio-region1
spec:
  volumeName: minio-region1-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
