apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: minio
spec:
  volumeName: minio-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
