apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-region1-pvc
  namespace: postgres-region1
spec:
  volumeName: postgres-region1-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
