apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-region1-pv
  namespace: postgres-region1
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /postgres-region1-volume
