apiVersion: v1
data:
  s3_secret_key: 'bWluaW9hZG1pbg=='
  session_secret: 'c3BvcmtsZXNzcHJlY2tsZXNzcGVrbGU='
  redis_url: 'cmVkaXM6Ly86cmVkaXNAcmVkaXMtbWFzdGVyLnJlZGlzLnN2Yy5jbHVzdGVyLmxvY2FsOjYzNzk='
  postgres_url: 'cG9zdGdyZXNxbDovL3NwZWNrbGU6c3BlY2tsZUBwb3N0Z3Jlc3FsLnBvc3RncmVzLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvc3BlY2tsZQo='
kind: Secret
metadata:
  name: server-vars
  namespace: speckle-server
type: Opaque
