#!/usr/bin/env sh
set -e
[ -n "$CI" ] && exit 0

#shellcheck source=/dev/null
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged

echo "🔍 looking for additional linter dependencies"

check_dependencies_available() {
  for i in "${@}"
  do
    if ! command -v "${i}"; then
      echo "No ${i} executable found skipping additional checks" >&2
      exit 0
    fi
  done
}

check_dependencies_available pre-commit hadolint helm shellcheck 

echo "All systems functional, running additional pre-commit checks..."
pre-commit run --all-files
