apiVersion: v1
kind: Service
metadata:
  name: speckle-webhook-service-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app: speckle-webhook-service
    project: speckle-server
spec:
  selector:
    app: speckle-webhook-service
    project: speckle-server
  ports:
    - protocol: TCP
      name: web
      port: 9095
      targetPort: metrics
