apiVersion: v1
kind: Service
metadata:
  name: speckle-webhook-service-metrics
  namespace: {{ .Values.namespace }}
  labels:
{{ include "webhook_service.labels" . | indent 4 }}
spec:
  selector:
    app: speckle-webhook-service
    project: speckle-server
  ports:
    - protocol: TCP
      name: web
      port: 9095
      targetPort: metrics
