apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "monitoring.name" $ }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "monitoring.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
{{ include "monitoring.selectorLabels" . | indent 6 }}
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              release: kube-prometheus-stack
      ports:
        - port: metrics
  egress:
    # postgres can be anywhere external or within the cluster
    # TODO: parse provided postgres and blob storage data and template to restrict egress accordingly
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
    - to:
        - namespaceSelector: {}
    # allow access to DNS
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
