apiVersion: v1
kind: Service
metadata:
  name: speckle-monitoring-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app: speckle-monitoring
    project: speckle-server
spec:
  selector:
    app: speckle-monitoring
    project: speckle-server
  ports:
    - protocol: TCP
      name: web
      port: 9092
      targetPort: metrics
