{{- if .Values.monitoring.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "monitoring.name" $ }}
  namespace: {{ .Values.namespace | quote }}
  labels:
{{ include "monitoring.labels" $ | indent 4 }}
  annotations:
    "kubernetes.io/enforce-mountable-secrets": "true"
automountServiceAccountToken: false
secrets:
  - name: {{ default .Values.secretName .Values.db.connectionString.secretName }}
{{- end -}}
