{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: speckle-monitoring-metrics
  namespace: {{ .Values.namespace }}
  labels:
{{ include "monitoring.labels" . | indent 4 }}
spec:
  selector:
    app: speckle-monitoring
    project: speckle-server
  ports:
    - protocol: TCP
      name: web
      port: {{ .Values.monitoring.port }}
      targetPort: metrics
{{- end }}
