name: Run all builds

# temporarely diabled while working on the rest
# on: workflow_dispatch
on:
  workflow_call:
    inputs:
      IMAGE_VERSION_TAG:
        required: true
        type: string

jobs:
  docker-build-server:
    runs-on: blacksmith
    name: Docker build server
    steps:
      - name: Build and push
        uses: useblacksmith/build-push-action@v1
        with:
          push: false
          tags: speckle/speckle-server:${{ inputs.IMAGE_VERSION_TAG }}
          file: ./packages/server/Dockerfile

  docker-build-frontend2:
    runs-on: blacksmith
    name: Docker build frontend2
    steps:
      - name: Build and push
        uses: useblacksmith/build-push-action@v1
        with:
          push: false
          tags: speckle/speckle-frontend-2:${{ inputs.IMAGE_VERSION_TAG }}
          file: ./packages/frontend-2/Dockerfile

  docker-build-preview-service:
    runs-on: blacksmith
    name: Docker build preview service
    steps:
      - name: Build and push
        uses: useblacksmith/build-push-action@v1
        with:
          push: false
          tags: speckle/speckle-preview-service:${{ inputs.IMAGE_VERSION_TAG }}
          file: ./packages/preview-service/Dockerfile

  docker-build-webhook-service:
    runs-on: blacksmith
    name: Docker build webhook service
    steps:
      - name: Build and push
        uses: useblacksmith/build-push-action@v1
        with:
          push: false
          tags: speckle/speckle-webhook-service:${{ inputs.IMAGE_VERSION_TAG }}
          file: ./packages/webhook-service/Dockerfile

  docker-build-fileimport-service:
    runs-on: blacksmith
    name: Docker build file import service
    steps:
      - name: Build and push
        uses: useblacksmith/build-push-action@v1
        with:
          push: false
          tags: speckle/speckle-fileimport-service:${{ inputs.IMAGE_VERSION_TAG }}
          file: ./packages/fileimport-service/Dockerfile

  docker-build-test-deploy:
    runs-on: blacksmith
    name: Docker build test deploy util
    steps:
      - name: Build and push
        uses: useblacksmith/build-push-action@v1
        with:
          push: false
          tags: speckle/speckle-test-deployment:${{ inputs.IMAGE_VERSION_TAG }} # TODO: fix tag,
          file: ./utils/test-deployment/Dockerfile

  docker-build-monitor-deployment:
    runs-on: blacksmith
    name: Docker build monitor container
    steps:
      - name: Build and push
        uses: useblacksmith/build-push-action@v1
        with:
          push: false
          tags: speckle/speckle-monitor-deployment:${{ inputs.IMAGE_VERSION_TAG }}
          file: ./packages/monitor-deployment/Dockerfile

  docker-build-docker-compose-ingress:
    runs-on: blacksmith
    name: Docker build docker compose ingress
    steps:
      - name: Build and push
        uses: useblacksmith/build-push-action@v1
        with:
          push: false
          tags: speckle/speckle-docker-compose-ingress:${{ inputs.IMAGE_VERSION_TAG }}
          file: ./utils/docker-compose-ingress/Dockerfile
