name: Test helm deployment

on: workflow_dispatch

jobs:
  verify-non-prod:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    if: github.ref != 'refs/heads/main'
    steps:
      - run: echo "This is a non-production deployment."

  get-version:
    needs: [verify-non-prod]
    name: Get version
    uses: ./.github/workflows/get-version.yml

  builds:
    needs: [verify-non-prod, get-version]
    uses: ./.github/workflows/builds.yml
    with:
      IMAGE_VERSION_TAG: ${{ needs.get-version.outputs.IMAGE_VERSION_TAG }}
      REGISTRY_DOMAIN: 'ghcr.io'
      REGISTRY_USERNAME: ${{ github.actor }}
      # REGISTRY_DOMAIN, REGISTRY_USERNAME, REGISTRY_TOKEN must allow pushing to the below IMAGE_PREFIX
      IMAGE_PREFIX: 'ghcr.io/specklesystems'
      PUBLISH: false # do not publish the sourcemaps or include the version in frontend-2 builds
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deployment-tests:
    needs: [builds, get-version]
    uses: ./.github/workflows/deployment-tests.yml
    with:
      IMAGE_VERSION_TAG: ${{ needs.get-version.outputs.IMAGE_VERSION_TAG }}
      REGISTRY_DOMAIN: ghcr.io
      REGISTRY_USERNAME: ${{ github.actor }}
      IMAGE_PREFIX: 'ghcr.io/specklesystems'
    secrets:
      REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
