# get-version:
#   outputs:
#     IMAGE_VERSION_TAG: ${{ steps.step3.outputs.IMAGE_VERSION_TAG }}
#   name: Get version
#   runs-on: blacksmith
#   defaults:
#     run:
#       working-directory: ./.github/workflows/scripts
#   steps:
#     - uses: actions/checkout@v4.2.2
#     - run: chmod +x ./get_version.sh ./common.sh
#     - run: ./get_version.sh
#     - run: echo "IMAGE_VERSION_TAG=${result}"
#     - run: echo "IMAGE_VERSION_TAG=${IMAGE_VERSION_TAG}" >> "$GITHUB_OUTPUT"

#-  run: cat workspace/env-vars >> $BASH_EN
# - run: echo "IMAGE_VERSION_TAG=${IMAGE_VERSION_TAG}"

# Builds

# get_version: # maybe there is a github action / param / or we do not even need it

# # gha https://github.com/pre-commit/action

# pre-commit:

# # checks

# test-server:
# test-server-no-ff: # look for permutiations strategy metric from test-server
# test-server-multiregion: # "
# test-frontend:
# test-viewer:
# test-objectsender:
# test-shared:
# test-preview-service: # we do not have tests here at the moment
# test-ui-components:

# # gha https://www.chromatic.com/docs/github-actions/

# ui-components-chromatic: # gha https://www.chromatic.com/docs/github-actions/

# # strandalone smoke test gha docker/build-push-action  build and push to branch id location

# docker-build:

# docker-build-server:
# docker-build-frontend:
# docker-build-webhooks:
# docker-build-file-imports:
# docker-build-previews:

# docker-build-test-container:
# docker-build-postgres-container:
# docker-build-monitor-container:
# docker-build-docker-compose-ingress:

# # standalone helm check

# deployment-test-helm-chart: # there big one here without running k8
