name: PR Pipeline

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # other running workflows get cancelled on the same branch

jobs:
  get-version:
    name: Get version
    uses: ./.github/workflows/get-version.yml

  tests:
    if: false # TODO: delete
    needs: [get-version]
    uses: ./.github/workflows/tests.yml
    with:
      IMAGE_VERSION_TAG: ${{ needs.get-version.outputs.IMAGE_VERSION_TAG }}
      DOCKERHUB_USERNAME: 'speckledevops'
    secrets: inherit

  builds:
    needs: [get-version]
    uses: ./.github/workflows/builds.yml
    with:
      IMAGE_VERSION_TAG: ${{ needs.get-version.outputs.IMAGE_VERSION_TAG }}
      DOCKERHUB_USERNAME: 'speckledevops'
      IMAGE_PREFIX: 'ghcr.io/specklesystems'
      PUBLISH: false # do not publish the sourcemaps or include the version in frontend-2 builds for pull requests
    secrets: inherit

  #TODO remove this job once the deployment tests are stable
  deployment-tests:
    needs: [builds, get-version]
    uses: ./.github/workflows/deployment-tests.yml
    with:
      IMAGE_VERSION_TAG: ${{ needs.get-version.outputs.IMAGE_VERSION_TAG }}
      DOCKERHUB_USERNAME: 'speckledevops'
      IMAGE_PREFIX: 'ghcr.io/specklesystems'
    secrets: inherit
