name: Pipeline test build

on: pull_request

jobs:
  ui-components-chromatic:
    name: UI components chromatic
    runs-on: blacksmith
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: useblacksmith/setup-node@v5
        with:
          node-version: 22
          cache: yarn
      - name: Build public packages
        run: yarn build:public
      - name: Run chromatic
        run: yarn chromatic
        working-directory: 'packages/ui-components'

  # TODO
  # test-preview-service

  # TODO:
  # docker-publish-frontend-2-sourcemaps

  # TODO: codecov

  # TODO: fix db error on multiregion test
