name: Pipeline test build

on: pull_request

jobs:
  get-version:
    outputs:
      IMAGE_VERSION_TAG: ${{ steps.step3.outputs.IMAGE_VERSION_TAG }}
    name: Get version
    runs-on: blacksmith
    defaults:
      run:
        working-directory: ./.github/workflows/scripts
    steps:
      - uses: actions/checkout@v4.2.2
      - run: chmod +x ./get_version.sh ./common.sh
      - run: ./get_version.sh
      - run: echo "IMAGE_VERSION_TAG=${result}"
      - run: echo "IMAGE_VERSION_TAG=${IMAGE_VERSION_TAG}" >> "$GITHUB_OUTPUT"

        # TODO:
        # - store_test_results:
        #    path: packages/server/reports
