name: Pipeline test build

on: pull_request

jobs:
  prepre-commit: # TODO: move to blacksmith
    name: Precommit check
    runs-on: ubuntu-latest
    container:
      image: speckle/pre-commit-runner:latest
    steps:
      # it clones a helmchart md outside the repo
      - name: Move into
        run: |
          mkdir -p app
          cd app
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - name: Set precommit
        run: pre-commit install-hooks --config ./.pre-commit-config.yaml
      - name: Install dependencies
        run: PUPPETEER_SKIP_DOWNLOAD=true PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 yarn --immutable
      - name: Build public packages
        run: yarn build:public
      - name: Run precommit
        run: ./.husky/pre-commit
      - name: Diff on failure
        if: failure()
        run: git --no-pager diff
