name: Pipeline test build

on: pull_request

jobs:
  # get-version:
  #   outputs:
  #     IMAGE_VERSION_TAG: ${{ steps.step6.outputs }}
  #   name: Get version
  #   runs-on: blacksmith
  #   defaults:
  #     run:
  #       working-directory: ./.github/workflows/scripts
  #   steps:
  #     - uses: actions/checkout@v4.2.2
  #     - run: git fetch origin 'refs/tags/*:refs/tags/*'
  #     - run: chmod +x ./get_version.sh ./common.sh
  #     - run: result=$(./get_version.sh)
  #     - run: echo "IMAGE_VERSION_TAG=${result}"
  #     - run: echo "${result}" >> "$GITHUB_OUTPUT"

  # # TODO:
  # docker-build-server:
  #   runs-on: blacksmith
  #   needs: [get-version]
  #   name: Docker build server
  #   steps:
  #     - name: Build and push
  #       uses: useblacksmith/build-push-action@v1
  #       with:
  #         push: false
  #         tags: speckle/speckle-server:${{ needs.get-version.outputs.IMAGE_VERSION_TAG }}
  #         file: ./packages/server/Dockerfile
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
