name: Pipeline test build

on: pull_request

jobs:
  get-version:
    outputs:
      IMAGE_VERSION_TAG: ${{ steps.step6.outputs.IMAGE_VERSION_TAG }}
    name: Get version
    runs-on: blacksmith
    defaults:
      run:
        working-directory: ./.github/workflows/scripts
    steps:
      - uses: actions/checkout@v4.2.2
      - run: git fetch origin 'refs/tags/*:refs/tags/*'
      - run: chmod +x ./get_version.sh ./common.sh
      - run: ./get_version.sh
      - run: echo "IMAGE_VERSION_TAG=${result}"
      - run: echo "IMAGE_VERSION_TAG=${IMAGE_VERSION_TAG}" >> "$GITHUB_OUTPUT"

  # TODO:
  docker-build-server:
    runs-on: blacksmith
    needs: [get-version]
    name: Docker build server
    steps:
      - name: Build and push
        uses: useblacksmith/build-push-action@v1
        with:
          push: false
          tags: speckle/speckle-server:${{ needs.get-version.outputs.IMAGE_VERSION_TAG }}
          file: ./packages/server/Dockerfile
