name: Pipeline test build

on: pull_request

jobs:
  prepre-commit:
    name: Precommit check
    runs-on: speckle/pre-commit-runner:latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: useblacksmith/setup-node@v5
        with:
          node-version: 22
          cache: yarn
      - name: Set precommit
        run: pre-commit install-hooks --config ./.pre-commit-config.deployment.yaml
      - name: Install dependencies
        run: PUPPETEER_SKIP_DOWNLOAD=true PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 yarn --immutable
      - name: Build public packages
        run: yarn build:public
      - name: Run precommit
        run: ./.husky/pre-commit
      - name: Diff on failure
        if: failure()
        run: git --no-pager diff
