name: Pipeline test build

on: pull_request

jobs:
  ui-components-chromatic:
    env:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }} # TODO: fix envbar
    name: UI components chromatic
    runs-on: blacksmith
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - uses: useblacksmith/setup-node@v5
        with:
          node-version: 22
          cache: yarn
      - name: Install dependencies
        run: PUPPETEER_SKIP_DOWNLOAD=true PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 yarn --immutable
      - name: Build public packages
        run: yarn build:public
      - name: Run chromatic
        run: yarn chromatic
        working-directory: 'packages/ui-components'

  # TODO: fix, shh error on cloning helmjson schema at .helm-readme-configuration.json
  # TODO: move to blacksmith
  pre-commit:
    name: Precommit check
    runs-on: ubuntu-latest
    container:
      image: speckle/pre-commit-runner:latest
      env:
        BLACKSMITH_CACHE_TOKEN: ${{ env.BLACKSMITH_CACHE_TOKEN }}
        BLACKSMITH_CACHE_URL: ${{ env.BLACKSMITH_CACHE_URL }}
        GITHUB_REPO_NAME: ${{ env.GITHUB_REPO_NAME }}
    defaults:
      run:
        working-directory: speckle
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          path: speckle
      - uses: actions/checkout@v4.2.2
        with:
          repository: bitnami-labs/readme-generator-for-helm
          path: readme-generator-for-helm
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - name: Set precommit
        run: pre-commit install-hooks --config ./.pre-commit-config.yaml
      - name: Install dependencies
        run: PUPPETEER_SKIP_DOWNLOAD=true PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 yarn --immutable
      - name: Build public packages
        run: yarn build:publicw
      - name: Run precommit
        run: ./.husky/pre-commit
      - name: Diff on failure
        if: failure()
        run: git --no-pager diff

  # TODO: codecov

  # TODO: fix db error on multiregion test
