name: Pipeline test build

on: workflow_dispatch

jobs:
  get-version:
    outputs:
      IMAGE_VERSION_TAG: ${{ steps.export-step.outputs.IMAGE_VERSION_TAG }}
    name: Get version
    runs-on: blacksmith
    steps:
      - uses: actions/checkout@v4.2.2
      - run: git fetch origin 'refs/tags/*:refs/tags/*'
      - run: chmod +x ./get_version.sh ./common.sh
        working-directory: ./.github/workflows/scripts
      - run: ./get_version.sh >> result
        working-directory: ./.github/workflows/scripts
      - run: echo "IMAGE_VERSION_TAG=$(cat result)"
        working-directory: ./.github/workflows/scripts
      - id: export-step
        run: echo "IMAGE_VERSION_TAG=$(cat result)" >> "$GITHUB_OUTPUT"
        working-directory: ./.github/workflows/scripts

  # # # TODO:
  docker-build-server:
    runs-on: blacksmith
    needs: [get-version]
    name: Docker build server
    steps:
      - name: Build and push
        uses: useblacksmith/build-push-action@v1
        with:
          push: false
          tags: speckle/speckle-server:${{ needs.get-version.outputs.IMAGE_VERSION_TAG }}
          file: ./packages/server/Dockerfile
